---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ROCcurve

<!-- badges: start -->
<!-- badges: end -->

The goal of ROCcurve is to ...

## Installation

You can install the development version of ROCcurve from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("tswanson222/ROCcurve")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ROCcurve)

# Fit a model with only one predictor
roc1 <- ROCcurve(y = mtcars$vs, X = mtcars$mpg)

# Or with multiple predictors
roc2 <- ROCcurve(y = mtcars$vs, X = mtcars[, 1:4])

summary(roc2)

# plot the ROC curve
plot(roc1)

# plot the PR curve
plot(roc1, type = 'prc')


# Fit PR curves
prc <- ROCcurve(y = mtcars$vs, X = mtcars$mpg, prc = TRUE)
plot(prc)

summary(prc)

# Conduct an AUC test
auc_test(mtcars, 'am', 'mpg', 'disp', nboot = 100, seed = 91, verbose = FALSE)
```

